---

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    # include the handler in your playbook
    - include_role:
        name: sedi.notify_teams
        public: true

    # highly recommended is to use a block in your main playbook
    # so you can catch failures within your tasks by "rescue"
    - block:

        - set_fact:
            sdteams_title: "{{ title }}"
            sdteams_message: "All went fine"
            sdteams_details: "Looks like my task ran just fine!"
            sdteams_status: "success"
            sdteams_button_url: "{{ url }}"

        # this will trigger the notification handler at the (very) end
        - shell: echo foo
          notify: sdteams_notify

        # handlers will only notify once at the very end but you might want to 
        # send a notification right NOW.
        # -> this is handled by "tasks_from: notify_NOW.yml".
        # note: this does not clear a triggered "sdteams_notify" handler, so if you use both 
        # ("notify: sdteams_notify" + notify_NOW.yml) then you will get 1 notify due to the handler
        # at the end and immediately any executed notify_NOW.yml.
        #
        # this is how to use it, of course you can specify all the sdteams variables
        # elsewhere, as usual:
        - include_role:
            name: sedi.notify_teams
            tasks_from: notify_NOW.yml
          vars:
            sdteams_status: success
            sdteams_message: "MS-Teams notify role released!"
            sdteams_details: "You can find it at Ansible-Galaxy and on Github. Check it out!"
            sdteams_button_text: "Galaxy"
            sdteams_button_url: "https://galaxy.ansible.com/sedi/notify_teams"
            sdteams_2nd_button_text: "Github"
            sdteams_2nd_button_url: "https://github.com/secure-diversITy/ansible_role_notify-teams"

        # if you want to test a failed task, enable the following but
        # do not disable the above. You will get only 1 (failure) notification:
        #- fail:
        #    msg: 'this task failed.. you will get a failure due to "rescue"'

      # important to also get notifies when failures occur above
      rescue:

        - set_fact:
            sdteams_title: "{{ title }}"
            sdteams_message: 'something failed in the regular play'
            sdteams_details: "{{ ansible_failed_result.msg }}"
            sdteams_status: "failure"
            sdteams_button_url: "{{ url }}"

        - name: Failed
          shell: "echo -e {{ ansible_failed_result.msg }}"
          notify: sdteams_notify
